### ISSUE TITLE
Adding option to read historic data from station and precipitation

### ISSUE THREAD

**Issue by asafHorvitz** [rooper149/OpenWeather#2]
Hi

Can you add an option to get historic data from station (synop or metar) ?

also is there an option to add precipitation ?

thanks

**Comment by ryancoopers** [comment]
I can most defiantly look into it, it's been quite a while since I've worked on this project.

What level of historic data are you looking for, if I remember correctly most stations only retain their data for about 24 hours. There might be some 3rd party databases that store it indefinitely though.
