### ISSUE TITLE
Is This Project Still in Development? 

### ISSUE THREAD

**Issue by uwbadgerdev** [rooper149/OpenWeather#7]
Hi,

I was wondering if anyone knew if this project was still in development. I tried the example in the readme and it doesn't match what is in the code.... So I am figuring the project has been 100% abandoned. 

Edit: Also the project website is non-working...

Any news would be helpful. I am looking to use this package for a project of mine.

Thanks!

**Comment by ryancoopers** [comment]
I updated the example to reflect the current nuget package. Admittedly, the API could be better and make use of more recent C# language and dotnet features, maybe I'll update it soon. Another thing to note is that the compiled stations list will also be out of date, it seems I last updated it 2 years ago.

**Comment by ryancoopers** [comment]
I have also updated the site to point directly to the GitHub pages page.

https://rooper149.github.io/OpenWeather/

**Comment by ryancoopers** [comment]
@uwbadgerdev I have updated the library a bit and made use of MicrosoftRX extensions which you can see in the new example in the ReadMe. I have also updated the stations list to the most recent. The Nuget package is still out of date, so feel free to just checkout the code and use it directly until I can release a new Nuget package.

**Comment by uwbadgerdev** [comment]
@rooper149 appreciate the update and the work on this! your the best!

**Comment by ryancoopers** [comment]
@uwbadgerdev A new NugetPackage has been uploaded https://www.nuget.org/packages/OpenWeather

**Comment by uwbadgerdev** [comment]
SWEEEEEET! Thanks!
