### ISSUE TITLE
AWC: The Text Data Server has been discontinued

### ISSUE THREAD

**Issue by Sunshine-ki** [rooper149/OpenWeather#9]
AWC discontinued TDS, see more information here: https://aviationweather.gov/dataserver/

Your link 

```
protected override string GenerateLookupUrl() => $"https://www.aviationweather.gov/adds/dataserver_current/httpparam?
```

not available

**Comment by ryancoopers** [comment]
@Sunshine-ki I have pushed changes to fix the issue and a new nuget package will be available shortly (OpenWeather 2.2.1). It seems there have been quite a few changes, but they (aviationweather.gov) still support the old style API for compatibility. I will open a case to possibly add the new API and some of the new features is provides.
